### ISSUE TITLE
Does it accept non-UTF8 `PathBuf`s on Linux?

### ISSUE THREAD

**Issue by vi** [udoprog/argwerk#8]
I.e. would it be 'Y' or 'N' in ["Invalid UTF-8" column](https://github.com/rosetta-rs/argparse-rosetta-rs?tab=readme-ov-file#results)?

Also does it accept `=` character between option and its value, e.g. `--limit=20` instead of `--limit 20`?

**Comment by udoprog** [comment]
Hi!

> I.e. would it be 'Y' or 'N' in ["Invalid UTF-8" column](https://github.com/rosetta-rs/argparse-rosetta-rs?tab=readme-ov-file#results)?

Yes, use `#[os]`.

> Also does it accept `=` character between option and its value, e.g. `--limit=20` instead of `--limit 20`?

I don't remember, but I don't think so. Of it does, the argument would have to be decodable to utf-8 given how argwerk works.

Hope that helps!
